version: '3'

services:

  database:
    image: "postgres:latest"
    container_name: database
    ports:
      - 5432:5432
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3000:3000
    links:
      - database
